"""The fifty-call regression suite, and the version-bump gate it feeds.

README I-04's risk table: "Model degrades after a vendor update | Medium | Pin
model version; regression test suite of 50 known calls; re-validate before any
version bump."

Two halves, and the second is the one that usually gets skipped:

  * `run_regression` puts a fixed set of calls through the real structuring
    path and scores the result field by field against a known-good answer.
  * `ModelPin` refuses to hand out a model identifier that has not passed. A
    regression suite nobody runs before a version bump is a regression suite
    that documents the degradation after it ships, so the pin is a gate rather
    than a report.

Scoring is per FIELD, not per note. A model that gets the chief complaint right
and drops every safety-net instruction would score well on any whole-note
similarity measure, and safety-net instructions are the part of a triage note
that gets read out in a deposition. Every field is worth the same, and the
report says which ones moved.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any, Iterable, Mapping, Sequence

from .fixtures import TriageCase
from .structure import NoteStructurer, StructuredNote

__all__ = [
    "FieldScore",
    "RegressionResult",
    "run_regression",
    "ModelPin",
    "ModelNotValidated",
    "REQUIRED_CALLS",
    "PASS_THRESHOLD",
]

#: README I-04: fifty known calls.
REQUIRED_CALLS = 50

#: Field-level agreement below this fails the suite. Not 1.0: the extraction is
#: a paraphrase task and an exact-match score of 1.0 across fifty calls would
#: mean the reference answers were generated by the same model being tested,
#: which measures nothing.
PASS_THRESHOLD = 0.95

#: No single field may sit below this, whatever the average says. A model that
#: emitted no safety-net instruction at all on half the corpus scored 0.50 on
#: that field and 0.9500 overall, and the pin accepted it -- which is the
#: whole-note averaging this module's docstring says it refuses to do, arriving
#: through the back door.
FIELD_PASS_THRESHOLD = 0.85

#: A suite that ran no adversarial case cannot report that none was missed. Both
#: of these are conditions on the CORPUS rather than on the model: 50 copies of
#: one twenty-second call, with grounding switched off, passed cleanly and
#: printed "0 missed adversarial drop(s)" -- text identical to a run that
#: actually caught them all.
MIN_DISTINCT_TRANSCRIPTS = 10
MIN_ADVERSARIAL_ITEMS = 3

_SCORED_FIELDS = (
    "chief_complaint",
    "symptom_onset",
    "symptoms_reported_present",
    "symptoms_explicitly_denied",
    "relevant_history_mentioned",
    "medications_mentioned",
    "advice_given_by_ma",
    "safety_net_instructions_given",
    "followup_discussed",
    "followup_timeframe",
    # Who the practice took the history from. Absent from this tuple, the
    # wrong-informant control had no regression coverage at all: a model that
    # renamed every caller in the corpus to the medical assistant -- a name
    # spoken on nearly every call, so it grounds -- scored a clean 1.0.
    "caller.name",
    "caller.relationship_to_patient",
)


def _extract(data: Mapping[str, Any], field_name: str) -> Any:
    """Read a scored field, including the two nested under `caller`."""
    if "." not in field_name:
        return data.get(field_name)
    parent, child = field_name.split(".", 1)
    return (data.get(parent) or {}).get(child)


class ModelNotValidated(RuntimeError):
    """Raised when a model identifier is used without a passing regression."""


def _normalise(value: Any) -> Any:
    if isinstance(value, str):
        return " ".join(value.lower().split())
    if isinstance(value, list):
        return sorted(_normalise(v) for v in value)
    if isinstance(value, dict):
        return {k: _normalise(v) for k, v in sorted(value.items())}
    return value


@dataclass
class FieldScore:
    field_name: str
    compared: int = 0
    agreed: int = 0
    examples: list[dict[str, Any]] = field(default_factory=list)

    @property
    def rate(self) -> float:
        return (self.agreed / self.compared) if self.compared else 1.0


@dataclass
class RegressionResult:
    model_id: str
    model_version: str
    prompt_hash: str
    calls: int
    fields: dict[str, FieldScore] = field(default_factory=dict)
    errors: list[dict[str, str]] = field(default_factory=list)
    ungrounded_drops: int = 0
    #: Declared adversarial items that were NOT removed. See `passes`.
    missed_drops: list[dict[str, Any]] = field(default_factory=list)
    #: Distinct hand-written transcripts behind the run. See `summary`.
    distinct_transcripts: int = 0
    #: How many declared-fabricated items the run actually exercised.
    adversarial_items: int = 0
    run_at: datetime | None = None

    @property
    def overall(self) -> float:
        compared = sum(f.compared for f in self.fields.values())
        agreed = sum(f.agreed for f in self.fields.values())
        return (agreed / compared) if compared else 0.0

    @property
    def worst_fields(self) -> list[FieldScore]:
        return sorted(self.fields.values(), key=lambda f: f.rate)[:5]

    def passes(
        self, *, required_calls: int = REQUIRED_CALLS, threshold: float = PASS_THRESHOLD
    ) -> bool:
        """Field agreement AND every declared adversarial item still removed.

        `missed_drops` is a separate, absolute condition rather than another
        term in the average, because averaging hides it. With grounding
        disabled entirely -- fabricated advice passing straight through to the
        chart -- field agreement was 0.988 and this returned True: the corpus
        only declares drops on a couple of fixtures, so switching off the
        control that stops the machine inventing clinical advice cost about one
        percentage point. A suite that green-lights a model with its safety
        control off is a report, not a gate.
        """
        return not self.blockers(required_calls=required_calls, threshold=threshold)

    def blockers(
        self, *, required_calls: int = REQUIRED_CALLS, threshold: float = PASS_THRESHOLD
    ) -> list[str]:
        """Every reason this run must not be pinned. Empty means it passes."""
        problems: list[str] = []
        if self.calls < required_calls:
            problems.append(f"only {self.calls} of {required_calls} calls completed")
        if self.errors:
            problems.append(f"{len(self.errors)} case(s) raised")
        if self.distinct_transcripts < MIN_DISTINCT_TRANSCRIPTS:
            problems.append(
                f"only {self.distinct_transcripts} distinct transcript(s); a "
                f"corpus of fewer than {MIN_DISTINCT_TRANSCRIPTS} is one call "
                "repeated, not a suite"
            )
        if self.adversarial_items < MIN_ADVERSARIAL_ITEMS:
            problems.append(
                f"only {self.adversarial_items} declared adversarial item(s) "
                f"exercised; below {MIN_ADVERSARIAL_ITEMS} the run cannot "
                "report that none was missed"
            )
        if self.missed_drops:
            problems.append(
                f"{len(self.missed_drops)} declared fabrication(s) survived: "
                + ", ".join(
                    f"{m['case']}.{m['field']}" for m in self.missed_drops[:3]
                )
            )
        weak = [
            f for f in self.fields.values()
            if f.compared and f.rate < FIELD_PASS_THRESHOLD
        ]
        if weak:
            problems.append(
                "field(s) below "
                f"{FIELD_PASS_THRESHOLD}: "
                + ", ".join(f"{f.field_name}={f.rate:.2f}" for f in weak)
            )
        if self.overall < threshold:
            problems.append(f"overall {self.overall:.4f} below {threshold}")
        return problems

    def summary(self) -> str:
        worst = ", ".join(f"{f.field_name}={f.rate:.2f}" for f in self.worst_fields)
        # The transcript count is in the summary, and the summary is what
        # ModelPin stores, because "50 calls" reads like fifty real calls. It is
        # fifteen hand-written transcripts tiled, and whoever reads this line at
        # the next version bump should know that before trusting the number.
        return (
            f"{self.model_id}@{self.model_version} prompt#{self.prompt_hash}: "
            f"{self.calls} calls over {self.distinct_transcripts} distinct "
            f"transcript(s), overall {self.overall:.4f}, "
            f"{len(self.errors)} error(s), {len(self.missed_drops)} missed "
            f"adversarial drop(s). Weakest: {worst}"
        )


def run_regression(
    structurer: NoteStructurer,
    cases: Sequence[TriageCase],
    *,
    transcriber: Any,
    recorder_factory: Any,
    run_at: datetime | None = None,
) -> RegressionResult:
    """Score a structurer against known-good extractions, field by field.

    `transcriber` and `recorder_factory` are injected so the suite runs against
    the REAL pipeline objects rather than a shortcut that feeds the structurer a
    transcript directly -- a regression suite that skips the transcript assembly
    would not catch a change in how speaker labels are presented to the model,
    which is exactly the kind of thing that silently changes an extraction.
    """
    result = RegressionResult(
        model_id="unknown",
        model_version="unknown",
        prompt_hash=structurer.prompt_hash,
        calls=0,
        run_at=run_at,
    )
    for name in _SCORED_FIELDS:
        result.fields[name] = FieldScore(name)
    result.distinct_transcripts = len({c.name.split("__r")[0] for c in cases})

    for case in cases:
        recording = recorder_factory(case)
        try:
            transcript = transcriber.transcribe(recording)
            note: StructuredNote = structurer.structure(
                transcript, patient_id=case.patient_id, user_id="system:regression"
            )
        except Exception as exc:  # noqa: BLE001 - an error IS the finding here
            result.errors.append({"case": case.name, "error": f"{type(exc).__name__}: {exc}"})
            continue

        result.calls += 1
        result.model_id = note.model_id
        result.model_version = note.model_version
        result.ungrounded_drops += len(note.dropped)

        # Every item the fixture declares as fabricated has to be gone. This is
        # the only check in the suite that looks at the safety control rather
        # than at extraction quality, and it is the only one that cannot be
        # traded off against a good score elsewhere.
        for field_name, items in (case.expect.get("expected_drops") or {}).items():
            result.adversarial_items += len(items)
            surviving = _extract(note.data, field_name) or []
            for item in items:
                if item in surviving:
                    result.missed_drops.append(
                        {"case": case.name, "field": field_name, "item": item}
                    )

        for name in _SCORED_FIELDS:
            expected = _normalise(case.expect.get("reference", {}).get(name, None))
            if expected is None:
                # Fall back to the fixture's own extraction, minus whatever the
                # grounding check is SUPPOSED to remove. A reference that
                # included the ungrounded items would mark the safety control as
                # a regression every time it worked.
                expected = _normalise(_expected_after_grounding(case, name))
            actual = _normalise(_extract(note.data, name))
            score = result.fields[name]
            score.compared += 1
            if actual == expected:
                score.agreed += 1
            elif len(score.examples) < 3:
                score.examples.append(
                    {"case": case.name, "expected": expected, "actual": actual}
                )
    return result


def _expected_after_grounding(case: TriageCase, field_name: str) -> Any:
    """The fixture's answer, minus the items the fixture DECLARES should drop.

    Note what this does not do: consult `note.dropped`. Subtracting whatever
    this run happened to remove makes expected equal actual by construction --
    a suite that scored 1.0000 with grounding sabotaged to delete every advice
    and safety-net instruction in the corpus, and `ModelPin.bump` accepted it.
    The expectation has to come from the fixture, which is the only thing in
    the loop that the model under test cannot influence.
    """
    value = _extract(case.extraction, field_name)
    declared = case.expect.get("expected_drops", {}).get(field_name)
    if not isinstance(value, list):
        # A scalar field the fixture declares as fabricated -- an invented
        # caller name -- becomes null, which is what the drop policy does to it.
        return None if declared else value
    return [item for item in value if item not in set(declared or ())]


@dataclass
class ModelPin:
    """A pinned model identity that will not move without a passing suite.

    Holds the identifier every production call uses. `bump()` refuses a new
    version unless a `RegressionResult` for that exact version passes, so the
    control README I-04 asks for lives in the code path rather than in a
    checklist item somebody ticks at 5pm on a Friday.
    """

    model_id: str
    model_version: str
    #: README 9.4: prompts are code. A pin that covers the model but not the
    #: prompt lets `STRUCTURING_SYSTEM_PROMPT` be edited with no revalidation,
    #: which is the same failure the pin exists to prevent, one layer up.
    prompt_hash: str = ""
    validated_on: date | None = None
    last_result_summary: str = ""

    def bump(self, result: RegressionResult, *, on: date) -> None:
        if not result.passes():
            raise ModelNotValidated(
                "refusing to pin a model that has not passed the regression "
                f"suite: {result.summary()}. Blocking: "
                + "; ".join(result.blockers())
                + ". README I-04 requires 50 known calls re-validated before "
                "any version bump."
            )
        self.model_id = result.model_id
        self.model_version = result.model_version
        self.prompt_hash = result.prompt_hash
        self.validated_on = on
        self.last_result_summary = result.summary()

    def require(
        self, model_id: str, model_version: str, prompt_hash: str | None = None
    ) -> None:
        """Assert that the model AND prompt about to be used are the validated ones."""
        if (model_id, model_version) != (self.model_id, self.model_version):
            raise ModelNotValidated(
                f"model {model_id}@{model_version} is not the pinned, validated "
                f"model ({self.model_id}@{self.model_version}); run the "
                "regression suite and bump the pin first"
            )
        if prompt_hash is not None and self.prompt_hash and prompt_hash != self.prompt_hash:
            raise ModelNotValidated(
                f"prompt {prompt_hash} is not the validated prompt "
                f"({self.prompt_hash}); prompts are code (README 9.4) and a "
                "prompt change needs the same revalidation a model change does"
            )
